require("abbas.options")
require("abbas.keymaps")
require("abbas.plugins")
require("abbas.colorscheme")
require("abbas.cmp")
-- there is a init.lua inside abbas/lsp so we don't need to require all files seperately
require("abbas.lsp")
require("abbas.telescope")
require("abbas.treesitter")
require("abbas.autopairs")
--require("abbas.nvim-tree")
require("abbas.bufferline")
require("abbas.comment")
require("abbas.lualine")
require("abbas.transparent")
